import { readFileSync, writeFileSync, existsSync, cpSync, rmSync, mkdirSync, readdirSync } from 'fs'
import { resolve, join } from 'path'
import { spawnSync } from 'child_process'
import { log, printBanner } from '../utils/logger.js'
import { Spinner } from '../utils/spinner.js'

/**
 * ─── Command: init ───────────────────────────────────────────────────────────
 * 初始化一个新的项目脚手架资产
 */
export async function cmdInit(args, FACTORY_VERSION, ROOT) {
    printBanner()

    // 1. 处理入参 (args 现在是一个数组 [...rest])
    const argsArray = Array.isArray(args) ? args : [args]
    const initialProjectName = argsArray.find(a => a && typeof a === 'string' && !a.startsWith('--'))
    const presetFlagIdx = argsArray.indexOf('--preset')
    let preset = presetFlagIdx !== -1 ? (argsArray[presetFlagIdx + 1] || '') : ''

    let projectName = initialProjectName

    // 载入 Inquirer (与主路由保持一致的动态载入)
    const inquirer = (await import('inquirer')).default

    // 获取项目名
    if (!projectName) {
        const answers = await inquirer.prompt([
            {
                type: 'input',
                name: 'projectName',
                message: '请输入新项目的名称:',
                default: 'my-factory-project',
                validate: i => i ? true : '项目名称不能为空'
            }
        ])
        projectName = answers.projectName
    }

    // 2. 选择预设栈
    if (!preset) {
        const loadingSpinner = new Spinner().start('正在智能载入项目底座预设库...')
        const presets = [
            { name: 'Vue3 + Element-Plus (后台管理系统 - 推荐)', value: 'vue3-element-admin' },
            { name: 'React + Ant-Design (后台管理系统)', value: 'react-antd-admin' },
            { name: 'Vue3 + Vant (移动端 H5)', value: 'vue3-vant-h5' },
            { name: '自定义模板 (NPM / Git)', value: 'custom' }
        ]
        loadingSpinner.stop()

        const { selectedPreset } = await inquirer.prompt([
            {
                type: 'select',
                name: 'selectedPreset',
                message: '请选择项目基础预设栈 (Presets):',
                choices: presets
            }
        ])
        preset = selectedPreset
    }

    if (preset === 'custom') {
        log.warn('自定义模板功能正在灰度中，目前支持以下内置预设:')
        log.gray('  - vue3-element-admin')
        log.gray('  - react-antd-admin')
        log.gray('  - vue3-vant-h5')
        process.exit(0)
    }

    const spinner = new Spinner().start(`正在初始化新项目: ${projectName} [${preset}]`)

    const dest = join(process.cwd(), projectName)
    if (existsSync(dest)) {
        spinner.fail(`目录已存在: ${dest}`)
        process.exit(1)
    }

    /**
     * 3. 寻找模板资产
     * 策略：
     * a. 如果是在库本身的 monorepo 环境下 (比如开发时)，找 ../{preset}
     * b. 如果是作为 npm package (npx) 安装的，找 ROOT/templates/base-{preset}
     */
    const monorepoPath = resolve(ROOT, '..', preset)
    const builtInPath = join(ROOT, 'templates', `base-${preset}`)

    let finalSrc = ''
    if (existsSync(monorepoPath) && readdirSync(monorepoPath).length > 2) {
        finalSrc = monorepoPath
    } else if (existsSync(builtInPath)) {
        finalSrc = builtInPath
    }

    if (!finalSrc) {
        spinner.fail(`找不到预设 [${preset}] 的模板资产。`)
        log.gray(`  已探测路径 A (Monorepo): ${monorepoPath} (存在: ${existsSync(monorepoPath)})`)
        log.gray(`  已探测路径 B (Built-in): ${builtInPath} (存在: ${existsSync(builtInPath)})`)
        log.gray('提示：如果是核心开发者，请确保模板目录已就绪并包含 package.json；如果是普通用户，请报告 BUG（可能该预设尚未发布）。')
        process.exit(1)
    }

    spinner.start(`从源拷贝资产 [${preset}] 至本地工作区...`)

    // 拷贝策略：排除 node_modules, dist, .git
    try {
        cpSync(finalSrc, dest, {
            recursive: true,
            filter: (src) => {
                const isIgnored = /node_modules|dist|\.git|tsbuildinfo/.test(src)
                return !isIgnored
            }
        })
        spinner.succeed(`底层源码拷贝已就绪`)
    } catch (err) {
        spinner.fail('资产拷贝过程中出现错误')
        console.error(err)
        process.exit(1)
    }

    // 4. 更新新项目的 package.json
    const pkgPath = join(dest, 'package.json')
    if (existsSync(pkgPath)) {
        try {
            const pkgRaw = readFileSync(pkgPath, 'utf-8')
            const pkg = JSON.parse(pkgRaw)
            pkg.name = projectName
            pkg.version = '1.0.0'
            pkg.description = `Project generated by FE-Auto-Factory v${FACTORY_VERSION} using preset [${preset}]`
            delete pkg.repository // 删除模版原有的仓库信息
            writeFileSync(pkgPath, JSON.stringify(pkg, null, 2), 'utf-8')
        } catch (e) {
            log.warn('无法解析模板 package.json，跳过元数据自动更新。')
        }
    }

    // 5. 创建工厂配置文件 .factory/config.json
    const factoryConfig = {
        projectName,
        preset,
        createdAt: new Date().toISOString(),
        factoryVersion: FACTORY_VERSION,
        skills: ['01-requirements', '02-development', '03-testing', '04-deployment', '05-component-reuse', '06-vision-snapshot'],
        schema: {
            pagesDir: 'schemas/pages'
        },
    }

    const factoryDir = join(dest, '.factory')
    if (!existsSync(factoryDir)) {
        mkdirSync(factoryDir, { recursive: true })
    }
    writeFileSync(join(factoryDir, 'config.json'), JSON.stringify(factoryConfig, null, 2), 'utf-8')

    // 📄 写入简单的初始化文档
    const docsDir = join(dest, 'docs')
    if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true })
    const initLog = `# ${projectName} 变更日志\n\n## [v1.0.0] - ${new Date().toLocaleDateString()}\n- ✅ 由 FE-Auto-Factory 驱动落地\n- 预设底座: ${preset}\n- 引擎版本: v${FACTORY_VERSION}\n`
    writeFileSync(join(docsDir, 'CHANGELOG.md'), initLog, 'utf-8')

    spinner.succeed(`项目 "${projectName}" 完美初始化！`)
    console.log('')
    log.gray(`🚀 开启赋能之路:`)
    log.gray(`  1. cd ${projectName}`)
    log.gray(`  2. npm install`)
    log.gray(`  3. npm run dev`)
    console.log('')
    log.info(`💡 接下来，开始注入您的业务图纸 (Schemas) 或 UI 设计稿吧！`)
}


